name: cheml
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.11
  - scipy=1.14.1
  - numpy=2.2.5
  - pandas=2.2.3
  - scikit-learn=1.6.1
  - fastapi=0.115.12
  - httpx=0.28.1
  - tqdm=4.67.1
  - pip=25.1
  - pytorch=2.6.0
  - pytorch-lightning=2.5.1
  - lightning=2.5.1
  - cachetools=5.5.2
  - python-jose=3.3.0
  - python-multipart=0.0.20
  - pip:
    - build==1.0.3
    - mlflow==2.21.3
    - "mlflow[auth]"
    - starlette==0.46.2
    - uvicorn==0.34.2
