name: cheml-dev
channels:
  - defaults
  - conda-forge
dependencies:
- pytest=8.3.5
- matplotlib=3.10.1
- pytest-datadir=1.6.1
- pytest-regressions=2.7.0
- pytest-asyncio=1.0.0
- pytest-mock=3.14.1
- ruff=0.11.7
- pre-commit=4.2.0
- invoke=2.2.0
- ipykernel=6.29.5
- pip:
  - build==1.2.2
  - autoflake==2.2.1
  - types-requests>=2.31.0
  - types-cachetools>=5.3.0
